config/routes.rb
Inout::Application.routes.draw do
  devise_for :users  
  
  resources :status_changes, only: [:create]
  match '/board', to: 'status_changes#board'
  match '/log', to: 'status_changes#log'
  
  root :to => 'home#index'
end

app/models/status_change.rb
class StatusChange < ActiveRecord::Base
  attr_accessible :in, :status, :created_at
  belongs_to :user
  
  validates :status, length: { maximum: 60 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  validates :name, presence: true, length: { maximum: 50 }
  
  has_many :status_changes, dependent: :destroy, :order => "created_at DESC"
  has_one :current_status, :class_name => "StatusChange", :order => 'created_at DESC'
  
  # Check if a user is currently in the office
  # Assume user is in if no records of status changes
  def is_in
   self.current_status.nil? || self.current_status.in
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
  def index
    if user_signed_in?
      flash.keep(:notice)
      redirect_to board_path
    end
  end
end

app/controllers/status_changes_controller.rb
class StatusChangesController < ApplicationController
  
  before_filter :authenticate_user!
  
  def board
    # Grab current user status information, set up new status change
    @current_user_is_in = current_user.is_in
    @status = @current_user_is_in ? nil : current_user.current_status.status
    @status_change = StatusChange.new
    
    @users = User.all(include: :current_status, order: "users.name ASC")
    respond_to do |format|
      format.json { 
        render :json => { 
          :html => (render_to_string('status_changes/_users', :layout => false, :formats => [:html] ))
        }
      }
      format.html
    end
  end
  
  def log
    @status_changes = current_user.status_changes
  end
  
  def create
    @status_change = current_user.status_changes.build(params[:status_change])
    @status_change.in = !current_user.is_in
    if @status_change.save
      flash[:success] = "Your status was successfully changed."
      redirect_to board_path
    else
      # Render the board again with error information
      @current_user_is_in = current_user.is_in
      @users = User.all(include: :current_status, order: "users.name ASC")
      render 'board'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/status_changes_helper.rb
module StatusChangesHelper
end

app/views/home/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to the In and Out Board!</h1>
  <h2>
    If you are a new user, please click <%= link_to("here", new_user_registration_path) %> to register.
    Otherwise, please click <%= link_to("here", new_user_session_path) %> to sign in. 
  </h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><a href="https://github.com/hansonwu/inout">View on GitHub</a></li>
      <li>Site Developed by <a href="http://about.me/hansonwu">Hanson Wu</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "In and Out Board", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to('Board', board_path) %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as: 
                <span class="user-name"><%= current_user.name %></span>
                <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to('Edit Account', edit_user_registration_path) %></li>
                <li><%= link_to('Activity Log', log_path) %></li>
                <li class="divider"></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path) %></li>
            <li><%= link_to('Register', new_user_registration_path) %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
  <head>
    <title>In and Out Board</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <% unless key == :timedout %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/status_changes/_change_status.html.erb
<div id="create-status-change">
  <% if @status_change.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@status_change.errors.count, "error") %> prohibited the status change:
      <ul>
      <% @status_change.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @status_change do |f| %>
    <% if @current_user_is_in %>
      <%= f.text_field :status, class: "input-small", placeholder: "Out Message (ex. Lunch, Vacation)" %>
      <%= f.submit 'Out!', class: "btn btn-danger" %>
    <% else %>
      <%= f.submit "Back In!", class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/status_changes/_create.html.erb
<div id="create-status-change">
  <% if @status_change.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@status_change.errors.count, "error") %> prohibited the status change:
      <ul>
      <% @status_change.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(@status_change) do |f| %>
    <% if @current_user_is_in %>
      <%= f.text_field :status, class: "input-small", placeholder: "Out Message (ex. Lunch, Vacation)" %>
      <%= f.submit 'Out!', class: "btn btn-danger" %>
    <% else %>
      <%= f.submit "Back In!", class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/status_changes/_users.html.erb
<table class="table" id="users-table">
  <thead>
    <tr><th><h3>Board</h3></th></tr>
  </thead>
  <% if @users.length > 1 %>
    <% @users.each do |user| %>
      <% unless user.id == current_user.id %>
      <tr class="other-user">
        <td>
          <h3><%= user.name %></h3>
            <% if user.current_status.nil? || user.current_status.in %>
              <span class="in-status">Available</span>
            <% else %>
              <span class="out-status">Not Available </span>
                <% if !user.current_status.status.empty? %>
                  <span class="status-message">(<%= user.current_status.status %>)</span>
                <% end %>
              </span>
            <% end %>
          </h4>
        </td>
      </tr>
      <% end %>
    <% end %>
  <% else %>
    <tr class="other-user"><td><h3>No other users were found.</h3></td></tr>
  <% end %>
</table>

app/views/status_changes/board.html.erb
<div id="board-wrapper">
  <div id="board">
    <table class="table current">
      <tbody>
        <tr class="current-user">
          <td>
            <div id="current-user-box">
              <h3>Me</h3>
              <% if @current_user_is_in %>
                <span class="in-status">Available</span>
              <% else %>
                <span class="out-status">Not Available </span>
                  <% if !(@status.nil? || @status.empty?) %>
                    <span class="status-message">(<%= @status %>)</span>
                  <% end %>
                </span>
              <% end %>
              <%= render 'change_status' %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
    <div id="refresh">
      <i class="icon-refresh"></i>
      <%= link_to 'Refresh now', board_path, :remote => true, :id => 'refresh-board' %>
    </div>
    <%= render 'users' %>
  </div>
</div>

app/views/status_changes/log.html.erb
<div id="board-wrapper">
  <div id="board">
    <h3>Activity Log</h3><br />
    <% if @status_changes.empty? %>
      <h4>No activity found. Go to the <%= link_to 'Board', board_path %> to change your status.</h4>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>Changed to</th>
            <th>Message</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          <% @status_changes.each do |status_change| %>
            <tr>
              <td>
                <% if status_change.in %>
                  <span class="in-status">Available</span>
                <% else %>
                  <span class="out-status">Not Available</span>
                <% end %>
              </td>
              <td><%= status_change.status %></td>
              <td><%= status_change.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>    
    <% end %>
  </div>
</div>